<?php 
namespace haydee\enums;

// define("GESTIONAR_PAGOS", 1);
// define("GESTIONAR_GASTOS", 2);
// define("GESTIONAR_MENSUALIDAD", 3);
// define("GESTIONAR_CAJA_CHICA", 4);
// define("GESTIONAR_CARTELERA_VIRTUAL", 5);
// define("GESTIONAR_APARTAMENTOS", 6);
// define("GESTIONAR_SOLICITUD_GASTO", 7);
// define("GESTIONAR_PRESUPUESTO", 8);
// define("GESTIONAR_ANIO_FISCAL", 9);
// define("GESTIONAR_CONFIGURACION", 10);
// define("GESTIONAR_PROVEEDORES", 11);
// define("GESTIONAR_BANCOS", 12);
// define("GESTIONAR_TIPO_GASTO", 13);
// define("GESTIONAR_USUARIOS", 14);
// define("GESTIONAR_REPORTES", 15);
// define("GESTIONAR_SEGURIDAD", 16);
// define("GESTIONAR_ROLES", 17);
// define("GESTIONAR_BITACORA", 18);
// define("GESTIONAR_MANTENIMIENTO", 19);
// define("GESTIONAR_HABITANTES", 21);
// define("GESTIONAR_PERMISOS", 22);
// define("GESTIONAR_MODULOS", 23);

enum Modulo: int 
{
    case GESTIONAR_PAGOS = 1;
    case GESTIONAR_GASTOS = 2;
    case GESTIONAR_MENSUALIDAD = 3;
    case GESTIONAR_CAJA_CHICA = 4;
    case GESTIONAR_CARTELERA_VIRTUAL = 5;
    case GESTIONAR_APARTAMENTOS = 6;
    case GESTIONAR_SOLICITUD_GASTO = 7;
    case GESTIONAR_PRESUPUESTO = 8;
    case GESTIONAR_ANIO_FISCAL = 9;
    case GESTIONAR_CONFIGURACION = 10;
    case GESTIONAR_PROVEEDORES = 11;
    case GESTIONAR_BANCOS = 12;
    case GESTIONAR_TIPO_GASTO = 13;
    case GESTIONAR_USUARIOS = 14;
    case GESTIONAR_REPORTES = 15;
    case GESTIONAR_SEGURIDAD = 16;
    case GESTIONAR_ROLES = 17;
    case GESTIONAR_BITACORA = 18;
    case GESTIONAR_MANTENIMIENTO = 19;
    case GESTIONAR_HABITANTES = 21;
    case GESTIONAR_PERMISOS = 22;
    case GESTIONAR_MODULOS = 23;
}

