<?php 

define("GESTIONAR_PAGOS", 1);
define("GESTIONAR_GASTOS", 2);
define("GESTIONAR_MENSUALIDAD", 3);
define("GESTIONAR_CONCILIACION_BANCARIA", 4);
define("GESTIONAR_CARTELERA_VIRTUAL", 5);
define("GESTIONAR_HABITANTES", 6);
define("GESTIONAR_PROPIETARIOS", 7);
define("GESTIONAR_CONFIGURACION", 8);
define("GESTIONAR_PROVEEDORES", 9);
define("GESTIONAR_APARTAMENTOS", 10);
// define("GESTIONAR_MENSUALIDAD", 11);
define("GESTIONAR_USUARIOS", 12);
define("GESTIONAR_REPORTES", 13);
define("GESTIONAR_SEGURIDAD", 14);
define("GESTIONAR_ROLES", 15);
define("GESTIONAR_BITACORA", 16);
define("GESTIONAR_BANCOS", 17);

?>