<?php 

define("GESTIONAR_PAGOS", 1);
define("GESTIONAR_GASTOS", 2);
define("GESTIONAR_MENSUALIDAD", 3);
define("GESTIONAR_CAJA_CHICA", 4);
define("GESTIONAR_CARTELERA_VIRTUAL", 5);
define("GESTIONAR_APARTAMENTOS", 6);
define("GESTIONAR_SOLICITUD_GASTO", 7);
define("GESTIONAR_PRESUPUESTO", 8);
define("GESTIONAR_ANIO_FISCAL", 9);
define("GESTIONAR_CONFIGURACION", 10);
define("GESTIONAR_PROVEEDORES", 11);
define("GESTIONAR_BANCOS", 12);
define("GESTIONAR_TIPO_GASTO", 13);
define("GESTIONAR_USUARIOS", 14);
define("GESTIONAR_REPORTES", 15);
define("GESTIONAR_SEGURIDAD", 16);
define("GESTIONAR_ROLES", 17);
define("GESTIONAR_BITACORA", 18);
define("GESTIONAR_MANTENIMIENTO", 19);

?>